site_name: XinFin Network
site_description: Xinfin Network

theme:
  name: 'readthedocs'
  custom_dir: material_override
  logo: 'images/logo.svg'
  favicon: 'images/favicon.ico'
  feature:
    tabs: true

markdown_extensions:
  - admonition
  - mdx_math:
      enable_dollar_delimiter: True
  - markdown.extensions.extra
  - markdown.extensions.toc:
      permalink: True
  - codehilite:
      guess_lang: false
  - markdown_fenced_code_tabs

extra_javascript:
    - js/MathJax.js?config=TeX-AMS_HTML

extra_css:
    - https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css
    - css/style.css

extra:
    disqus:
    social:
        - type: 'github'
          link: 'https://github.com/xinfinorg'
        - type: 'twitter'
          link: 'https://twitter.com/xinfinf'
        - type: 'reddit'
          link: 'https://www.reddit.com/r/xinfin/'
        - type: 'facebook'
          link: 'https://www.facebook.com/pages/xinfin'
        - type: 'telegram'
          link: 'https://t.me/xinfintalk'
        - type: 'medium'
          link: 'https://medium.com/xinfin'

site_url: https://docs.xinfin.org
repo_url: https://github.com/XinFinOrg/Docs-XF
repo_name: XinFinOrg/Docs-XF

nav:
    - General:
      - Introduction: index.md
      - Use cases: general/utilities.md
      - Networks: general/networks.md
      - FAQ: general/faq.md
      - About: general/about.md

    - Get started:
      - Products overview: get-started/productoverview.md
      - Hybrid Blockchain: get-started/hybblock.md
      - Smart Contract: get-started/smartcont.md
      - How DPOS Works?: get-started/hdpwork.md
      - XinFin DPOS Consensus: get-started/XDC.md
      - POW Replaced with DPOS: get-started/POW-DPOS.md
      - Connecting Legacy Systems: get-started/ConnLeg.md
      - Build with XinFin Hybrid Network: get-started/hybnet.md
      - Set up Master Nodes: get-started/Setupmn.md
      - Create DAPP Environment: get-started/cde.md
      - Set up Loyalty Token on XinFin.Network: get-started/lyl.md

    - XinFin Explorer:
      - Features: xinfinexp/features.md

    - XinFin Original Wallet:
      - Features: XinFinWallet/features.md

    - XinFin Android Wallet:
      - Features: XinFinAndWallet/features.md

    - Current Requirement:
      - Requirement: Requirement/req.md

    - XinFin Media:
      - Articles: media/articles.md

    - Whitepapers and research:
      - Technical whitepaper: wp-and-research/technical-whitepaper.md

    - XinFin Community Support:
      - Community: Community/support.md

copyright: If you wish to improve this site, please <a href="https://github.com/XinFinOrg/Docs-XF/docs/issues/new"><i class="fa fa-github"></i> open an issue</a> or <a href="https://github.com/XinFinOrg/Docs-XF/docs/compare"><i class="fa fa-github"></i> send a pull request</a>.<br>XinFin Network.
